"""The data model — two tables with a one-to-many relationship.

A Conversation has many Messages. In Sequelize terms:
  Conversation.hasMany(Message);  Message.belongsTo(Conversation);
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db import Base


class Conversation(Base):
    __tablename__ = "conversations"

    # A UUID string as the primary key (generated by the app, like before).
    id: Mapped[str] = mapped_column(Text, primary_key=True)
    title: Mapped[str] = mapped_column(Text, default="New chat")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    # Rolling summary of older messages, so we don't resend the whole transcript.
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    # How many of the oldest messages the summary already covers.
    summarized_count: Mapped[int] = mapped_column(default=0, server_default="0")

    # The Python-side link to this conversation's messages, newest loading last.
    messages: Mapped[list["Message"]] = relationship(
        back_populates="conversation",
        order_by="Message.id",
        cascade="all, delete-orphan",  # deleting a convo deletes its messages
    )


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(primary_key=True)  # auto-incrementing
    # The foreign key: each message belongs to exactly one conversation.
    conversation_id: Mapped[str] = mapped_column(
        ForeignKey("conversations.id", ondelete="CASCADE"), index=True
    )
    role: Mapped[str] = mapped_column(Text)  # "user" or "assistant"
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    conversation: Mapped["Conversation"] = relationship(back_populates="messages")
