"""add summary fields to conversations

Revision ID: 25ae4e9df2e7
Revises: fdbe2e3b5659
Create Date: 2026-10-08 16:27:55.035099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ae4e9df2e7'
down_revision: Union[str, Sequence[str], None] = 'fdbe2e3b5659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summarized_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summarized_count')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
